CREATE SCHEMA BAZA;

CREATE TABLE BAZA.BIBLIOTEKA
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naslov VARCHAR(50) NOT NULL,
ekstenzija VARCHAR(3) NOT NULL,
podatak BLOB(20M),
PRIMARY KEY (id)
);

alter table BAZA.BIBLIOTEKA
add autor varchar(50) not null;

CREATE TABLE BAZA.RIJECI
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naslov VARCHAR(50) NOT NULL,
ekstenzija VARCHAR(3) NOT NULL,
rijeci LONG VARCHAR NOT NULL,
stranica INT NOT NULL,
PRIMARY KEY (id)
);

SELECT * FROM BAZA.RIJECI;